FROM python:3.10

ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

COPY . .


EXPOSE 8000

CMD ["python", "manage.py","runserver" ,"0.0.0.0:8000"]

