# Generated by Django 4.2.6 on 2023-10-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svc_i_park',
            name='PC',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='svc_i_park',
            name='PT',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
